---

- name: Install AWS packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip
    - awscli
  when: zookeeper.aws_cluster_autodiscover.enabled

- name: Install Python libraries
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - boto
  when: zookeeper.aws_cluster_autodiscover.enabled

- name: Get local instance facts
  become: yes
  ec2_facts:
  when: zookeeper.aws_cluster_autodiscover.enabled

- name: Get local instance tags
  become: yes
  ec2_tag:
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: local_ec2_tags
  when: zookeeper.aws_cluster_autodiscover.enabled

- name: Get remote zookeeper facts
  become: yes
  ec2_remote_facts:
    filters: "{{ zookeeper.aws_cluster_autodiscover.lookup_filter }}"
    region: "{{ ansible_ec2_placement_region }}"
  register: remote_zookeeper_instances
  when: zookeeper.aws_cluster_autodiscover.enabled

- name: Setup myid
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.data_dir }}/myid"
    src: myid.j2
  notify:
   - restart zookeeper

- name: Setup zoo.cfg file
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.conf_dir }}/zoo.cfg"
    mode: 0644
    src: zoo.cfg.j2
  notify:
   - restart zookeeper

- name: Create Zookeeper log4j config
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.conf_dir }}/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart zookeeper

- name: Setup Zookeeper environment config
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.conf_dir }}/environment"
    mode: 0644
    src: environment.j2
  notify:
    - restart zookeeper

- name: Start Zookeeper service
  become: yes
  service:
    name: zookeeper
    state: started

- name: Flush handlers to ensure Zookeeper is up to date
  meta: flush_handlers

- name: Wait for Zookeeper port
  wait_for:
    port: "{{ zookeeper.client_port }}"
    state: started
    timeout: 30
